"use client";

import { FormEvent, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { getAdminSettingsData } from "@/db/queries/admin";
import {
  createFaqAction, createSkillAction, createSkillCategoryAction, createTimelineEntryAction,
  deleteFaqAction, deleteSkillAction, deleteSkillCategoryAction, deleteTimelineEntryAction,
  updateFaqAction, updateSkillAction, updateSkillCategoryAction, updateTimelineEntryAction,
  createAboutTechnologyAction, deleteAboutTechnologyAction, updateAboutTechnologyAction,
} from "@/app/admin/(protected)/settings/actions";
import styles from "./AdminShell.module.css";
import SiteSettingsForm from "./SiteSettingsForm";

type Data = Awaited<ReturnType<typeof getAdminSettingsData>>;
type Subsection = "profile" | "skills" | "technologies" | "timeline" | "faq";

export default function AboutContentManager({ data, images }: { data: Data; images: Data["images"] }) {
  const [subsection, setSubsection] = useState<Subsection>("profile");
  return <>
    <nav className={styles.quickLinks} aria-label="About settings">{(["profile", "skills", "technologies", "timeline", "faq"] as const).map((tab) => <button aria-pressed={subsection === tab} className={`${styles.quickLink} ${subsection === tab ? styles.selectedTab : ""}`} key={tab} onClick={() => setSubsection(tab)} type="button">{tab[0].toUpperCase() + tab.slice(1)}</button>)}</nav>
    {subsection === "profile" && <><p className={styles.editorHelp}>The About page’s “Currently” list and quotation are static presentation content; they are not database-backed fields managed here.</p>{data.settings ? <SiteSettingsForm group="about" media={images} settings={data.settings} /> : <section className={styles.statCard}>Site settings have not been initialized in the database.</section>}</>}
    {subsection === "skills" && <SkillsManager data={data} />}
    {subsection === "technologies" && <AboutTechnologiesManager rows={data.technologies} images={images} />}
    {subsection === "timeline" && <TimelineManager rows={data.timeline} />}
    {subsection === "faq" && <FaqManager rows={data.faqs} />}
  </>;
}

function AboutTechnologiesManager({ rows, images }: { rows: Data["technologies"]; images: Data["images"] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  function payload(form: FormData) { return { label: form.get("label"), mediaId: form.get("mediaId") || null, position: Number(form.get("position")), active: form.get("active") === "on" }; }
  function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); startTransition(async () => { const result = await createAboutTechnologyAction(payload(form)); setMessage(result.success ? "Technology created." : `Could not create technology (${result.error}).`); if (result.success) { formElement.reset(); router.refresh(); } }); }
  function update(event: FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await updateAboutTechnologyAction({ ...payload(form), id }); setMessage(result.success ? "Technology saved." : `Could not save technology (${result.error}).`); if (result.success) router.refresh(); }); }
  return <div className={styles.managerStack}>
    <section className={styles.managerCard}><h3>About technology marquee</h3><p className={styles.editorHelp}>The required label is always shown. Logo selection is optional and uses Media Library.</p><a className={styles.actionButton} href="/admin/media">Upload or manage images in Media Library</a></section>
    <form className={styles.managerCard} onSubmit={create}><h3>Add technology</h3><TechnologyFields images={images} position={String(Math.max(-1, ...rows.map((row) => row.position)) + 1)} /><button className={styles.saveButton} disabled={pending} type="submit">Add technology</button></form>
    {rows.map((row) => <form className={styles.managerCard} key={row.id} onSubmit={(event) => update(event, row.id)}><h3>Technology · {row.label}</h3><TechnologyFields images={images} row={row} position={String(row.position)} /><div className={styles.managerActions}><button className={styles.actionButton} disabled={pending} type="submit">Save</button><button className={styles.actionButton} disabled={pending} onClick={(event) => { event.preventDefault(); if (!window.confirm(`Delete “${row.label}” from the marquee?`)) return; startTransition(async () => { const result = await deleteAboutTechnologyAction(row.id); setMessage(result.success ? "Technology deleted." : `Could not delete technology (${result.error}).`); if (result.success) router.refresh(); }); }} type="button">Delete</button></div></form>)}
    {message && <Feedback>{message}</Feedback>}
  </div>;
}

function TechnologyFields({ images, row, position }: { images: Data["images"]; row?: Data["technologies"][number]; position: string }) {
  return <div className={styles.settingsGrid}><Input defaultValue={row?.label ?? ""} label="Label (required)" name="label" required /><label className={styles.field}><span>Logo (optional)</span><select defaultValue={row?.mediaId ?? ""} name="mediaId"><option value="">Text only</option>{images.filter((image) => image.mimeType.startsWith("image/")).map((image) => <option key={image.id} value={image.id}>{image.filename}</option>)}</select></label><Input defaultValue={position} label="Position" name="position" type="number" min={0} /><label className={styles.checkField}><input defaultChecked={row?.active ?? true} name="active" type="checkbox" /> Active</label></div>;
}

function SkillsManager({ data }: { data: Data }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  function createCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const input = { name: f.get("name"), slug: f.get("slug"), description: f.get("description") || null, position: Number(f.get("position")) }; startTransition(async () => { const result = await createSkillCategoryAction(input); setMessage(result.success ? "Skill category created." : `Could not create category (${result.error}).`); if (result.success) router.refresh(); }); }
  function createSkill(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const input = skillPayload(f); startTransition(async () => { const result = await createSkillAction(input); setMessage(result.success ? "Skill created." : `Could not create skill (${result.error}).`); if (result.success) router.refresh(); }); }
  return <div className={styles.managerStack}>
    <form className={styles.managerCard} onSubmit={createCategory}><h3>Add skill category</h3><div className={styles.settingsGrid}><Input label="Name" name="name" required /><Input label="Slug" name="slug" required /><Input label="Description" name="description" /><Input defaultValue={String(data.skillCategories.length)} label="Position" name="position" type="number" /></div><button className={styles.saveButton} disabled={pending} type="submit">Add category</button></form>
    {data.skillCategories.map((category) => <form className={styles.managerCard} key={category.id} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); const input = { id: category.id, name: f.get("name"), slug: f.get("slug"), description: f.get("description") || null, position: Number(f.get("position")) }; startTransition(async () => { const result = await updateSkillCategoryAction(input); setMessage(result.success ? "Category saved." : `Could not save category (${result.error}).`); if (result.success) router.refresh(); }); }}><h3>Category · {category.name}</h3><div className={styles.settingsGrid}><Input defaultValue={category.name} label="Name" name="name" required /><Input defaultValue={category.slug} label="Slug" name="slug" required /><Input defaultValue={category.description ?? ""} label="Description" name="description" /><Input defaultValue={String(category.position)} label="Position" name="position" type="number" /></div><div className={styles.managerActions}><button className={styles.actionButton} disabled={pending} type="submit">Save</button><button className={styles.actionButton} disabled={pending} onClick={(event) => { event.preventDefault(); if (!window.confirm(`Delete category “${category.name}” and all its skills?`)) return; startTransition(async () => { const result = await deleteSkillCategoryAction(category.id); setMessage(result.success ? "Category deleted." : `Could not delete category (${result.error}).`); if (result.success) router.refresh(); }); }} type="button">Delete</button></div></form>)}
    <form className={styles.managerCard} onSubmit={createSkill}><h3>Add skill</h3>{data.skillCategories.length ? <SkillFields data={data} defaultPosition={String(data.skills.length)} /> : <p className={styles.dashboardEmpty}>Create a category before adding skills.</p>}{Boolean(data.skillCategories.length) && <button className={styles.saveButton} disabled={pending} type="submit">Add skill</button>}</form>
    {data.skills.map((skill) => <form className={styles.managerCard} key={skill.id} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); startTransition(async () => { const result = await updateSkillAction({ ...skillPayload(f), id: skill.id }); setMessage(result.success ? "Skill saved." : `Could not save skill (${result.error}).`); if (result.success) router.refresh(); }); }}><h3>Skill · {skill.name}</h3><SkillFields data={data} defaultPosition={String(skill.position)} row={skill} /><div className={styles.managerActions}><button className={styles.actionButton} disabled={pending} type="submit">Save</button><button className={styles.actionButton} disabled={pending} onClick={(event) => { event.preventDefault(); if (!window.confirm(`Delete skill “${skill.name}”?`)) return; startTransition(async () => { const result = await deleteSkillAction(skill.id); setMessage(result.success ? "Skill deleted." : `Could not delete skill (${result.error}).`); if (result.success) router.refresh(); }); }} type="button">Delete</button></div></form>)}
    {message && <Feedback>{message}</Feedback>}
  </div>;
}

function SkillFields({ data, defaultPosition, row }: { data: Data; defaultPosition: string; row?: Data["skills"][number] }) {
  return <div className={styles.settingsGrid}><label className={styles.field}><span>Category</span><select defaultValue={row?.categoryId ?? data.skillCategories[0]?.id} name="categoryId" required>{data.skillCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><Input defaultValue={row?.name ?? ""} label="Name" name="name" required /><Input defaultValue={row?.slug ?? ""} label="Slug" name="slug" required /><Input defaultValue={row?.description ?? ""} label="Description" name="description" /><Input defaultValue={row?.details ?? ""} label="Details" name="details" /><label className={styles.field}><span>Icon media</span><select defaultValue={row?.iconMediaId ?? ""} name="iconMediaId"><option value="">No icon</option>{data.images.map((image) => <option key={image.id} value={image.id}>{image.filename}</option>)}</select></label><Input defaultValue={defaultPosition} label="Position" name="position" type="number" /></div>;
}

function skillPayload(form: FormData) { return { categoryId: form.get("categoryId"), name: form.get("name"), slug: form.get("slug"), description: form.get("description") || null, details: form.get("details") || null, iconMediaId: form.get("iconMediaId") || null, position: Number(form.get("position")) }; }

function TimelineManager({ rows }: { rows: Data["timeline"] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  function payload(f: FormData) { return { year: Number(f.get("year")), title: f.get("title"), description: f.get("description"), tag: f.get("tag") || null, position: Number(f.get("position")), active: f.get("active") === "on" }; }
  function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); startTransition(async () => { const result = await createTimelineEntryAction(payload(f)); setMessage(result.success ? "Timeline entry created." : `Could not create entry (${result.error}).`); if (result.success) router.refresh(); }); }
  return <div className={styles.managerStack}><form className={styles.managerCard} onSubmit={create}><h3>Add timeline entry</h3><TimelineFields position={String(Math.max(-1, ...rows.map((row) => row.position)) + 1)} /><button className={styles.saveButton} disabled={pending} type="submit">Add entry</button></form>{rows.map((row, index) => <form className={styles.managerCard} key={row.id} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); startTransition(async () => { const result = await updateTimelineEntryAction({ ...payload(f), id: row.id }); setMessage(result.success ? "Timeline entry saved." : `Could not save entry (${result.error}).`); if (result.success) router.refresh(); }); }}><TimelineFields row={row} position={String(index)} maxPosition={rows.length - 1} /><div className={styles.managerActions}><button className={styles.actionButton} disabled={pending} type="submit">Save</button><button className={styles.actionButton} disabled={pending} onClick={(event) => { event.preventDefault(); if (!window.confirm(`Delete timeline entry “${row.title}”?`)) return; startTransition(async () => { const result = await deleteTimelineEntryAction(row.id); setMessage(result.success ? "Timeline entry deleted." : `Could not delete entry (${result.error}).`); if (result.success) router.refresh(); }); }} type="button">Delete</button></div></form>)}{message && <Feedback>{message}</Feedback>}</div>;
}
function TimelineFields({ row, position, maxPosition }: { row?: Data["timeline"][number]; position: string; maxPosition?: number }) { return <div className={styles.settingsGrid}><Input defaultValue={String(row?.year ?? new Date().getFullYear())} label="Year" name="year" type="number" /><Input defaultValue={row?.title ?? ""} label="Title" name="title" required /><Input defaultValue={row?.tag ?? ""} label="Tag" name="tag" /><Input defaultValue={position} label="Position" name="position" type="number" min={0} max={maxPosition} /><Textarea defaultValue={row?.description ?? ""} label="Description" name="description" /><label className={styles.checkField}><input defaultChecked={row?.active ?? true} name="active" type="checkbox" /> Active</label></div>; }

function FaqManager({ rows }: { rows: Data["faqs"] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  function payload(f: FormData) { return { question: f.get("question"), answer: f.get("answer"), position: Number(f.get("position")), active: f.get("active") === "on" }; }
  function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); startTransition(async () => { const result = await createFaqAction(payload(f)); setMessage(result.success ? "FAQ created." : `Could not create FAQ (${result.error}).`); if (result.success) router.refresh(); }); }
  return <div className={styles.managerStack}><form className={styles.managerCard} onSubmit={create}><h3>Add FAQ</h3><FaqFields position={String(Math.max(-1, ...rows.map((row) => row.position)) + 1)} /><button className={styles.saveButton} disabled={pending} type="submit">Add FAQ</button></form>{rows.map((row, index) => <form className={styles.managerCard} key={row.id} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); startTransition(async () => { const result = await updateFaqAction({ ...payload(f), id: row.id }); setMessage(result.success ? "FAQ saved." : `Could not save FAQ (${result.error}).`); if (result.success) router.refresh(); }); }}><FaqFields row={row} position={String(index)} maxPosition={rows.length - 1} /><div className={styles.managerActions}><button className={styles.actionButton} disabled={pending} type="submit">Save</button><button className={styles.actionButton} disabled={pending} onClick={(event) => { event.preventDefault(); if (!window.confirm("Permanently delete this FAQ?")) return; startTransition(async () => { const result = await deleteFaqAction(row.id); setMessage(result.success ? "FAQ deleted." : `Could not delete FAQ (${result.error}).`); if (result.success) router.refresh(); }); }} type="button">Delete</button></div></form>)}{message && <Feedback>{message}</Feedback>}</div>;
}
function FaqFields({ row, position, maxPosition }: { row?: Data["faqs"][number]; position: string; maxPosition?: number }) { return <div className={styles.settingsGrid}><Textarea defaultValue={row?.question ?? ""} label="Question" name="question" required /><Textarea defaultValue={row?.answer ?? ""} label="Answer" name="answer" required /><Input defaultValue={position} label="Position" name="position" type="number" min={0} max={maxPosition} /><label className={styles.checkField}><input defaultChecked={row?.active ?? true} name="active" type="checkbox" /> Active</label></div>; }

function Input({ label, name, defaultValue = "", required = false, type = "text", min, max }: { label: string; name: string; defaultValue?: string; required?: boolean; type?: string; min?: number; max?: number }) { return <label className={styles.field}><span>{label}</span><input defaultValue={defaultValue} max={max} min={min} name={name} required={required} type={type} /></label>; }
function Textarea({ label, name, defaultValue = "", required = false }: { label: string; name: string; defaultValue?: string; required?: boolean }) { return <label className={styles.field}><span>{label}</span><textarea defaultValue={defaultValue} name={name} required={required} rows={3} /></label>; }
function Feedback({ children }: { children: string }) { return <p className={styles.formMessage} aria-live="polite" role="status">{children}</p>; }
