"use client";

import Image from "next/image";
import { useState } from "react";
import { BLOG_BLOCK_TYPES } from "@/lib/blog/block-schema";
import { classifyEmbedSource, classifyVideoSource } from "@/lib/blog/video-source";
import type { EditorFieldErrors } from "@/lib/admin/editor-validation";
import styles from "./AdminShell.module.css";

type Block = { id: string; type: string; position: number; data: Record<string, unknown> };
type Media = { id: string; filename: string; mimeType: string; url: string };
const initialData: Record<string, Record<string, unknown>> = {
  heading: { text: "", level: 2 }, paragraph: { text: "" }, image: { url: "", alt: "", caption: "" },
  gallery: { images: [{ url: "", alt: "", caption: "" }] }, video: { url: "", title: "" },
  quote: { text: "", author: "" }, list: { items: [""], ordered: false }, code: { code: "", language: "", filename: "" },
  table: { columns: ["Column 1"], rows: [[""]] }, comparison: { columns: ["Option A", "Option B"], rows: [["", ""]] },
  callout: { text: "", title: "", variant: "info" }, tool: { name: "", description: "", url: "" }, embed: { url: "", title: "", caption: "" },
};

function isPreviewableImageUrl(value: string) {
  try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:"; }
  catch { return value.startsWith("/") && !value.startsWith("//"); }
}

export default function ArticleBlockCanvas({ initial, media, errors }: { initial: Block[]; media: Media[]; errors: EditorFieldErrors }) {
  const [blocks, setBlocks] = useState(initial.map((block) => ({ ...block, data: { ...block.data } })));
  const [type, setType] = useState<string>(BLOG_BLOCK_TYPES[0]);
  function update(id: string, data: Record<string, unknown>) { setBlocks((old) => old.map((block) => block.id === id ? { ...block, data } : block)); }
  function move(index: number, delta: number) { const target = index + delta; if (target < 0 || target >= blocks.length) return; setBlocks((old) => { const next = [...old]; [next[index], next[target]] = [next[target], next[index]]; return next; }); }
  return <section className={styles.settingsSection}><h2>Article content</h2><p className={styles.editorHelp}>Add and arrange structured blocks. Each block shows the fields and guidance for its public presentation.</p><div className={styles.canvasAdd}><label className={styles.field}><span>Block type</span><select value={type} onChange={(event) => setType(event.target.value)}>{BLOG_BLOCK_TYPES.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><button className={styles.actionButton} type="button" onClick={() => setBlocks((old) => [...old, { id: crypto.randomUUID(), type, position: old.length, data: { ...initialData[type] } }])}>Add block</button></div><input name="blocksPayload" type="hidden" value={JSON.stringify(blocks.map((block, position) => ({ ...block, position })))} readOnly />
    {!blocks.length && <p className={styles.dashboardEmpty}>No content blocks yet. Add a block to build this article.</p>}
    <div className={styles.canvasStack}>{blocks.map((block, index) => <ArticleBlockCard block={block} blockCount={blocks.length} errors={errors} index={index} key={block.id} media={media} move={move} onDelete={() => setBlocks((old) => old.filter((item) => item.id !== block.id))} update={update} />)}</div>
  </section>;
}

function ArticleBlockCard({ block, blockCount, errors, index, media, move, onDelete, update }: { block: Block; blockCount: number; errors: EditorFieldErrors; index: number; media: Media[]; move: (index: number, delta: number) => void; onDelete: () => void; update: (id: string, data: Record<string, unknown>) => void }) {
  const path = `blocks.${block.id}`;
  const blockError = errors[path];
  const hasErrors = Object.keys(errors).some((key) => key === path || key.startsWith(`${path}.`));
  return <article className={styles.canvasBlock} data-block-path={path} data-invalid={hasErrors ? "true" : undefined}>
    <header className={styles.canvasHeader}><strong>{String(index + 1).padStart(2, "0")} / {block.type.toUpperCase()} <span aria-label={hasErrors ? "Block has validation errors" : "Block ready"}>{hasErrors ? "✕" : "✓"}</span></strong><div className={styles.rowActions}><button className={styles.actionButton} type="button" aria-label={`Move ${block.type} up`} disabled={!index} onClick={() => move(index, -1)}>↑</button><button className={styles.actionButton} type="button" aria-label={`Move ${block.type} down`} disabled={index >= blockCount - 1} onClick={() => move(index, 1)}>↓</button><button className={styles.actionButton} type="button" onClick={onDelete}>Delete block</button></div></header>
    {blockError && <p className={styles.fieldError} role="alert">{blockError}</p>}
    <BlockFields block={block} media={media} path={path} update={(data) => update(block.id, data)} />
  </article>;
}

function BlockFields({ block, media, path, update }: { block: Block; media: Media[]; path: string; update: (data: Record<string, unknown>) => void }) {
  const data = block.data;
  const set = (key: string, value: unknown) => update({ ...data, [key]: value });
  const textField = (key: string, label: string, helper?: string, multiline = false) => <label className={styles.field} key={key}><span>{label}</span>{multiline ? <textarea data-validation-path={`${path}.${key}`} rows={4} value={String(data[key] ?? "")} onChange={(event) => set(key, event.target.value)} /> : <input data-validation-path={`${path}.${key}`} value={String(data[key] ?? "")} onChange={(event) => set(key, event.target.value)} />}{helper && <small className={styles.blockHelp}>{helper}</small>}</label>;
  const imageFields = (key = "url", label = "Image") => <><label className={styles.field}><span>{label} from Media Library</span><select value={String(data[key] ?? "")} onChange={(event) => set(key, event.target.value)}><option value="">Select an image</option>{media.filter((item) => item.mimeType.startsWith("image/")).map((item) => <option key={item.id} value={item.url}>{item.filename}</option>)}</select><small className={styles.blockHelp}>The existing article schema stores the selected media URL in this block. Upload images in <a href="/admin/media" target="_blank" rel="noreferrer">Media Library</a>.</small></label>{textField(key, `${label} URL`, "Or paste a full HTTP(S) image URL.")}{typeof data[key] === "string" && isPreviewableImageUrl(String(data[key])) && <Image className={styles.blockPreviewImage} src={String(data[key])} alt="" width={640} height={400} unoptimized />}</>;
  const help = (text: string) => <p className={styles.blockHelp}>{text}</p>;
  if (block.type === "heading") return <div className={styles.canvasFields}>{textField("text", "Heading", "Use headings to divide the article into scannable sections.")}<label className={styles.field}><span>Heading level</span><select value={String(data.level ?? 2)} onChange={(event) => set("level", Number(event.target.value))}>{[2, 3, 4].map((level) => <option key={level} value={level}>H{level}</option>)}</select></label></div>;
  if (block.type === "paragraph") return <>{textField("text", "Paragraph text", "Plain text is rendered as a paragraph; HTML is displayed as text, never executed.", true)}<p className={styles.blockPreviewText}>{String(data.text ?? "")}</p></>;
  if (block.type === "image") return <>{help("Choose an image from Media Library or paste its full URL. Alt text is required for accessible article images.")}<div className={styles.canvasFields}>{imageFields()}{textField("alt", "Alt text", "Describe the information conveyed by the image.")}{textField("caption", "Caption (optional)")}</div></>;
  if (block.type === "gallery") {
    const images = Array.isArray(data.images) ? data.images as Record<string, string>[] : [];
    const setImages = (next: Record<string, string>[]) => set("images", next);
    const shift = (i: number, delta: number) => { const target = i + delta; if (target < 0 || target >= images.length) return; const next = [...images]; [next[i], next[target]] = [next[target], next[i]]; setImages(next); };
    return <>{help("Add one or more images. Select each image from Media Library or paste its URL, then provide alt text. Use arrows to set display order.")}{images.map((image, i) => <div className={styles.canvasSubBlock} key={`${block.id}-image-${i}`}><header className={styles.canvasHeader}><strong>IMAGE {i + 1}</strong><div className={styles.rowActions}><button className={styles.actionButton} type="button" disabled={i === 0} aria-label={`Move image ${i + 1} up`} onClick={() => shift(i, -1)}>↑</button><button className={styles.actionButton} type="button" disabled={i === images.length - 1} aria-label={`Move image ${i + 1} down`} onClick={() => shift(i, 1)}>↓</button><button className={styles.actionButton} type="button" onClick={() => setImages(images.filter((_, n) => n !== i))}>Remove image</button></div></header><label className={styles.field}><span>Choose media image</span><select value={image.url ?? ""} onChange={(event) => setImages(images.map((item, n) => n === i ? { ...item, url: event.target.value } : item))}><option value="">Select an image</option>{media.filter((item) => item.mimeType.startsWith("image/")).map((item) => <option key={item.id} value={item.url}>{item.filename}</option>)}</select></label><label className={styles.field}><span>Image URL</span><input data-validation-path={`${path}.image-${i}.url`} value={image.url ?? ""} onChange={(event) => setImages(images.map((item, n) => n === i ? { ...item, url: event.target.value } : item))} /></label><label className={styles.field}><span>Alt text</span><input data-validation-path={`${path}.image-${i}.alt`} value={image.alt ?? ""} onChange={(event) => setImages(images.map((item, n) => n === i ? { ...item, alt: event.target.value } : item))} /></label><label className={styles.field}><span>Caption (optional)</span><input value={image.caption ?? ""} onChange={(event) => setImages(images.map((item, n) => n === i ? { ...item, caption: event.target.value } : item))} /></label>{isPreviewableImageUrl(image.url) && <Image className={styles.blockPreviewImage} src={image.url} alt="" width={640} height={400} unoptimized />}</div>)}<button className={styles.actionButton} data-validation-path={`${path}.images`} type="button" onClick={() => setImages([...images, { url: "", alt: "", caption: "" }])}>Add gallery image</button></>;
  }
  if (block.type === "video") {
    const source = classifyVideoSource(String(data.url ?? ""));
    return <>{help("Use a YouTube or Vimeo video URL, or a direct MP4, WebM, or MOV file URL. The public article plays supported sources inline. Other sites may open externally instead.")}{textField("url", "Video source URL", "YouTube, Vimeo, .mp4, .webm, or .mov")}{textField("title", "Accessible video title (optional)")}{source.type === "direct" ? <video className={styles.blockVideoPreview} controls preload="metadata" aria-label={String(data.title || "Video preview")}><source src={source.url} type={source.mimeType} />Your browser does not support inline video playback.</video> : source.type === "youtube" || source.type === "vimeo" ? <div className={styles.blockEmbedPreview}><iframe src={source.url} title={String(data.title || "Video preview")} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div> : data.url ? <p className={styles.fieldError}>Unsupported video source. Use YouTube, Vimeo, MP4, WebM, or MOV.</p> : null}</>;
  }
  if (block.type === "embed") {
    const source = classifyEmbedSource(String(data.url ?? ""));
    return <>{help("Paste a YouTube or Vimeo video URL. The article converts it to a safe provider embed; no iframe HTML is accepted. The destination must permit iframe embedding. Some providers send frame-blocking policies; if the preview is blank, use the external link fallback shown to readers.")}{textField("url", "Embed URL", "YouTube or Vimeo page URL; arbitrary website URLs are not embedded.")}{textField("title", "Frame title (optional)")}{textField("caption", "Caption (optional)")}{source ? <div className={styles.blockEmbedPreview}><iframe src={source.url} title={String(data.title || "Embed preview")} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div> : data.url ? <p className={styles.fieldError}>No supported embed preview. Choose a YouTube or Vimeo URL.</p> : null}</>;
  }
  if (block.type === "quote") return <><div className={styles.canvasFields}>{textField("text", "Quote", "The quote is rendered in a visually distinct block.", true)}{textField("author", "Attribution (optional)")}</div><blockquote className={styles.blockQuotePreview}>{String(data.text ?? "")}{data.author ? <cite>— {String(data.author)}</cite> : null}</blockquote></>;
  if (block.type === "list") { const items = Array.isArray(data.items) ? data.items as string[] : []; return <><label className={styles.field}><span>List style</span><select value={data.ordered === true ? "ordered" : "unordered"} onChange={(event) => set("ordered", event.target.value === "ordered")}><option value="unordered">Bulleted list</option><option value="ordered">Numbered list</option></select></label>{items.map((item, i) => <div className={styles.canvasSubBlock} key={`${block.id}-item-${i}`}><label className={styles.field}><span>List item {i + 1}</span><input data-validation-path={`${path}.item-${i}`} value={item} onChange={(event) => set("items", items.map((value, n) => n === i ? event.target.value : value))} /></label><button className={styles.actionButton} type="button" onClick={() => set("items", items.filter((_, n) => n !== i))}>Remove item</button></div>)}<button className={styles.actionButton} data-validation-path={`${path}.items`} type="button" onClick={() => set("items", [...items, ""])}>Add list item</button></>; }
  if (block.type === "code") return <>{help("Code is rendered as escaped text in a preformatted block. HTML and scripts are not executed.")}<div className={styles.canvasFields}>{textField("filename", "Code title (optional)")}{textField("language", "Language (optional)")}</div>{textField("code", "Code", "Whitespace and line breaks are preserved.", true)}<pre className={styles.blockCodePreview}><code>{String(data.code ?? "")}</code></pre></>;
  if (block.type === "table" || block.type === "comparison") {
    const comparison = block.type === "comparison";
    const columns = Array.isArray(data.columns) ? data.columns as string[] : [];
    const rows = Array.isArray(data.rows) ? data.rows as string[][] : [];
    const setColumns = (next: string[]) => set("columns", next);
    const setRows = (next: string[][]) => set("rows", next);
    return <>{help(comparison ? "Each column is a side or option. Add at least two sides, name each one, then add rows for the comparison points. A separate overall title is not part of the current block format." : "Columns become accessible table headers. Each row must contain one value for every column.")}<h4 className={styles.blockSubheading}>{comparison ? "Comparison sides" : "Table column headers"}</h4>{columns.map((column, c) => <div className={styles.canvasSubBlock} key={`${block.id}-column-${c}`}><label className={styles.field}><span>{comparison ? `Side ${c + 1}` : `Header ${c + 1}`}</span><input data-validation-path={`${path}.column-${c}`} value={column} onChange={(event) => setColumns(columns.map((value, n) => n === c ? event.target.value : value))} /></label><button className={styles.actionButton} type="button" disabled={columns.length <= (comparison ? 2 : 1)} onClick={() => { setColumns(columns.filter((_, n) => n !== c)); setRows(rows.map((row) => row.filter((_, n) => n !== c))); }}>Remove column</button></div>)}<button className={styles.actionButton} data-validation-path={`${path}.columns`} type="button" onClick={() => { setColumns([...columns, comparison ? `Option ${columns.length + 1}` : `Column ${columns.length + 1}`]); setRows(rows.map((row) => [...row, ""])); }}>Add {comparison ? "side" : "column"}</button><h4 className={styles.blockSubheading}>{comparison ? "Comparison points" : "Table rows"}</h4>{rows.map((row, r) => <div className={styles.canvasSubBlock} key={`${block.id}-row-${r}`}><strong>{comparison ? `Point ${r + 1}` : `Row ${r + 1}`}</strong><div className={styles.canvasGrid}>{columns.map((column, c) => <label className={styles.field} key={c}><span>{comparison ? `${column} · point ${r + 1}` : `${column} · row ${r + 1}`}</span><input data-validation-path={`${path}.cell-${r}-${c}`} value={row[c] ?? ""} onChange={(event) => setRows(rows.map((values, n) => n === r ? values.map((cell, k) => k === c ? event.target.value : cell) : values))} /></label>)}</div><button className={styles.actionButton} type="button" onClick={() => setRows(rows.filter((_, n) => n !== r))}>Remove row</button></div>)}<button className={styles.actionButton} data-validation-path={`${path}.rows`} type="button" onClick={() => setRows([...rows, columns.map(() => "")])}>Add {comparison ? "comparison point" : "table row"}</button>{comparison && <div className={styles.blockComparisonPreview}>{columns.map((column, c) => <div key={c}><strong>{column}</strong>{rows.map((row, r) => <p key={r}>{row[c]}</p>)}</div>)}</div>}{!comparison && columns.length > 0 && <div className={styles.blockTablePreview}><table><thead><tr>{columns.map((column, i) => <th key={i}>{column}</th>)}</tr></thead><tbody>{rows.map((row, r) => <tr key={r}>{columns.map((_, c) => <td key={c}>{row[c]}</td>)}</tr>)}</tbody></table></div>}</>;
  }
  if (block.type === "callout") return <><label className={styles.field}><span>Callout style</span><select value={String(data.variant ?? "info")} onChange={(event) => set("variant", event.target.value)}>{["info", "success", "warning", "note"].map((variant) => <option key={variant}>{variant}</option>)}</select></label><div className={styles.canvasFields}>{textField("title", "Title (optional)")}{textField("text", "Callout content", "The title and content appear in a highlighted callout.", true)}</div><aside className={styles.blockCalloutPreview}><strong>{String(data.title ?? "")}</strong><p>{String(data.text ?? "")}</p></aside></>;
  if (block.type === "tool") return <><div className={styles.canvasFields}>{textField("name", "Tool name", "Required label shown to readers.")}{textField("url", "Tool URL (optional)", "A valid HTTP(S) URL creates an external link.")}</div>{textField("description", "Description (optional)", undefined, true)}<aside className={styles.blockToolPreview}><strong>{String(data.name ?? "Tool name")}</strong><p>{String(data.description ?? "")}</p></aside></>;
  return <p className={styles.fieldError}>This block type has no editor fields.</p>;
}
