"use client";
import { FormEvent, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createFooterExploreItemAction, deleteFooterExploreItemAction, reorderFooterExploreItemsAction, updateFooterExploreItemAction } from "@/app/admin/(protected)/settings/actions";
import styles from "./AdminShell.module.css";
type Item = { id: string; label: string; url: string; active: boolean; position: number };
export default function FooterExploreManager({ initial }: { initial: Item[] }) {
 const router=useRouter(); const [rows,setRows]=useState(initial); const [label,setLabel]=useState(""); const [url,setUrl]=useState(""); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
 function add(e:FormEvent){e.preventDefault(); startTransition(async()=>{const result=await createFooterExploreItemAction({label,url,active:true,position:Math.max(-1,...rows.map(r=>r.position))+1}); setMessage(result.success?"Explore item added.":`Could not add item (${result.error}).`); if(result.success){setLabel("");setUrl("");router.refresh();}});}
 function move(i:number,d:number){const t=i+d;if(t<0||t>=rows.length)return;setRows(old=>{const a=[...old];[a[i],a[t]]=[a[t],a[i]];return a.map((x,position)=>({...x,position}));});}
 return <div className={styles.managerStack}><p className={styles.editorHelp}>Active links appear in 02. EXPLORE. This list is separate from the reference and download links in Resources.</p><form className={styles.resourceCreate} onSubmit={add}><label className={styles.field}><span>Label</span><input value={label} onChange={e=>setLabel(e.target.value)} required/></label><label className={styles.field}><span>URL</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="/blog or https://…" required/></label><button className={styles.saveButton} disabled={pending}>Add item</button></form>
 {rows.map((row,i)=><article className={styles.resourceRow} key={row.id}><label className={styles.field}><span>Label</span><input value={row.label} onChange={e=>setRows(old=>old.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/></label><label className={styles.field}><span>URL</span><input value={row.url} onChange={e=>setRows(old=>old.map((x,n)=>n===i?{...x,url:e.target.value}:x))}/></label><label className={styles.positionField}><span>Position</span><input min="0" type="number" value={row.position} onChange={e=>setRows(old=>old.map((x,n)=>n===i?{...x,position:Number(e.target.value)}:x))}/></label><label className={styles.checkField}><input type="checkbox" checked={row.active} onChange={e=>setRows(old=>old.map((x,n)=>n===i?{...x,active:e.target.checked}:x))}/> Active</label><div className={styles.rowActions}><button className={styles.actionButton} disabled={i===0} type="button" aria-label="Move up" onClick={()=>move(i,-1)}>↑</button><button className={styles.actionButton} disabled={i===rows.length-1} type="button" aria-label="Move down" onClick={()=>move(i,1)}>↓</button><button className={styles.actionButton} disabled={pending} type="button" onClick={()=>startTransition(async()=>{const result=await updateFooterExploreItemAction(row);setMessage(result.success?"Explore item saved.":`Could not save (${result.error}).`);if(result.success)router.refresh();})}>Save</button><button className={styles.actionButton} disabled={pending} type="button" onClick={()=>startTransition(async()=>{const result=await deleteFooterExploreItemAction(row.id);setMessage(result.success?"Explore item deleted.":`Could not delete (${result.error}).`);if(result.success)router.refresh();})}>Delete</button></div></article>)}
 <button className={styles.quickLink} disabled={pending||!rows.length} type="button" onClick={()=>startTransition(async()=>{const result=await reorderFooterExploreItemsAction(rows.map((r,position)=>({id:r.id,position})));setMessage(result.success?"Explore order saved.":`Could not save order (${result.error}).`);if(result.success)router.refresh();})}>Save order</button>{message&&<p className={styles.formMessage} role="status" aria-live="polite">{message}</p>}</div>;
}
