"use client";

import { useState } from "react";
import styles from "./AdminShell.module.css";
import { PROJECT_BLOCK_TYPES as blocks, PROJECT_LINK_TYPES, PROJECT_MEDIA_ROLES, PROJECT_SECTION_TYPES as sections } from "@/lib/projects/editor-options";
type Block = { id?: string; type: string; position: number; data: Record<string, unknown> };
type Section = { id?: string; type: string; title?: string | null; anchor?: string | null; position: number; blocks: Block[] };
type Media = { mediaId: string; role: string; position: number; caption?: string | null; altTextOverride?: string | null };
type Link = { type: string; label: string; url: string; position: number };
const makeData = (type: string): Record<string, unknown> => ({ rich_text: { content: "" }, quote: { quote: "", author: "" }, image: { mediaId: "" }, gallery: { mediaIds: [] }, problem_list: { items: [""] }, objective_list: { items: [""] }, technology_list: { items: [""] }, process_steps: { steps: [{ title: "", description: "" }] }, metrics: { metrics: [{ value: "", label: "" }] }, roadmap: { items: [{ phase: "", title: "", description: "" }] }, callout: { title: "", content: "" } } as Record<string, Record<string, unknown>>)[type] ?? {};

export default function ProjectBlockCanvas({ initial, availableMedia, initialMedia, initialLinks }: { initial: Section[]; availableMedia: { id: string; filename: string }[]; initialMedia: Media[]; initialLinks: Link[] }) {
  const [rows, setRows] = useState(initial.map((s) => ({ ...s, blocks: s.blocks.map((b) => ({ ...b, data: { ...b.data } })) })));
  const [media, setMedia] = useState(initialMedia);
  const [links, setLinks] = useState(initialLinks);
  const [newSection, setNewSection] = useState<string>(sections[0]);
  const update = (si: number, bi: number, data: Record<string, unknown>) => setRows((old) => old.map((s, i) => i === si ? { ...s, blocks: s.blocks.map((b, j) => j === bi ? { ...b, data } : b) } : s));
  return <section className={styles.settingsSection}><h2>Project content</h2><p className={styles.editorHelp}>Build sections from the project block types supported by the existing renderer.</p>
    <input type="hidden" name="sectionsPayload" value={JSON.stringify(rows.map((s, position) => ({ ...s, position, blocks: s.blocks.map((b, p) => ({ ...b, position: p })) })))} readOnly />
    <div className={styles.canvasAdd}><label className={styles.field}><span>New section type</span><select value={newSection} onChange={(e) => setNewSection(e.target.value)}>{sections.map((s) => <option key={s}>{s}</option>)}</select></label><button className={styles.actionButton} type="button" onClick={() => setRows((old) => [...old, { id: crypto.randomUUID(), type: newSection, title: "", anchor: "", position: old.length, blocks: [] }])}>Add section</button></div>
    <div className={styles.canvasStack}>{rows.map((section, si) => { const sectionPath = `sections.${section.id ?? `position-${section.position}`}`; return <article className={styles.canvasBlock} key={section.id ?? `section-${si}`}><header className={styles.canvasHeader}><strong>SECTION {si+1} · {section.type.toUpperCase()}</strong><div className={styles.rowActions}><button type="button" className={styles.actionButton} onClick={() => setRows((old) => old.filter((_,i) => i !== si))}>Delete section</button></div></header><div className={styles.canvasFields}><label className={styles.field}><span>Section type</span><select value={section.type} onChange={(e) => setRows((old) => old.map((s,i) => i === si ? { ...s, type: e.target.value } : s))}>{sections.map((s) => <option key={s}>{s}</option>)}</select></label><Field label="Title" value={section.title ?? ""} onChange={(v) => setRows((old) => old.map((s,i) => i === si ? { ...s, title:v } : s))}/><Field label="Anchor" value={section.anchor ?? ""} onChange={(v) => setRows((old) => old.map((s,i) => i === si ? { ...s, anchor:v } : s))}/></div><div className={styles.canvasStack}>{section.blocks.map((block, bi) => { const blockPath = `${sectionPath}.blocks.${block.id ?? `position-${block.position}`}`; return <article className={styles.canvasSubBlock} data-block-path={blockPath} key={block.id ?? `${si}-${bi}`}><header className={styles.canvasHeader}><strong>{block.type.toUpperCase()}</strong><div className={styles.rowActions}><button type="button" className={styles.actionButton} disabled={!bi} onClick={() => setRows((old) => old.map((s,i) => i === si ? { ...s, blocks: (() => {const a=[...s.blocks]; [a[bi-1],a[bi]]=[a[bi],a[bi-1]]; return a;})() } : s))}>↑</button><button type="button" className={styles.actionButton} disabled={bi === section.blocks.length-1} onClick={() => setRows((old) => old.map((s,i) => i === si ? { ...s, blocks: (() => {const a=[...s.blocks]; [a[bi+1],a[bi]]=[a[bi],a[bi+1]]; return a;})() } : s))}>↓</button><button type="button" className={styles.actionButton} onClick={() => setRows((old) => old.map((s,i) => i === si ? { ...s, blocks: s.blocks.filter((_,j) => j !== bi) } : s))}>Delete</button></div></header><label className={styles.field}><span>Block type</span><select value={block.type} onChange={(e) => update(si,bi,makeData(e.target.value))}>{blocks.map((t) => <option key={t}>{t}</option>)}</select></label><ProjectFields block={block} media={availableMedia} path={`${blockPath}.data`} update={(data) => update(si,bi,data)} /></article>; })}</div>
      <div className={styles.canvasAdd}><label className={styles.field}><span>Add block</span><select id={`block-type-${si}`} defaultValue={blocks[0]}>{blocks.map((t) => <option key={t}>{t}</option>)}</select></label><button className={styles.actionButton} type="button" onClick={() => { const select = document.getElementById(`block-type-${si}`) as HTMLSelectElement; const type = select.value; setRows((old) => old.map((s,i) => i === si ? { ...s, blocks: [...s.blocks, { id: crypto.randomUUID(), type, position: s.blocks.length, data: makeData(type) }] } : s)); }}>Add block</button></div>
    </article>; })}</div>
    <h3>Media assignments</h3><input name="mediaPayload" type="hidden" value={JSON.stringify(media)} readOnly/><div className={styles.canvasStack}>{media.map((item,i) => <div className={styles.canvasFields} key={i}><label className={styles.field}><span>Media</span><select data-validation-path={`media.${i}.mediaId`} value={item.mediaId} onChange={(e) => setMedia((old) => old.map((m,n) => n===i ? {...m,mediaId:e.target.value}:m))}><option value="">Select media</option>{availableMedia.map((m) => <option key={m.id} value={m.id}>{m.filename}</option>)}</select></label><label className={styles.field}><span>Role</span><select value={item.role} onChange={(e) => setMedia((old) => old.map((m,n) => n===i ? {...m,role:e.target.value}:m))}>{PROJECT_MEDIA_ROLES.map((v) => <option key={v}>{v}</option>)}</select></label><Field label="Caption" value={item.caption ?? ""} onChange={(v) => setMedia((old) => old.map((m,n) => n===i ? {...m,caption:v}:m))}/><Field label="Alt text override" value={item.altTextOverride ?? ""} onChange={(v) => setMedia((old) => old.map((m,n) => n===i ? {...m,altTextOverride:v}:m))}/><button className={styles.actionButton} type="button" onClick={() => setMedia((old) => old.filter((_,n) => n!==i))}>Remove</button></div>)}<button className={styles.actionButton} type="button" onClick={() => setMedia((old) => [...old,{mediaId:"",role:"gallery",position:old.length}])}>Add media assignment</button></div>
    <h3>Project links</h3><input name="linksPayload" type="hidden" value={JSON.stringify(links)} readOnly/><div className={styles.canvasStack}>{links.map((link,i) => <div className={styles.canvasFields} key={i}><label className={styles.field}><span>Type</span><select value={link.type} onChange={(e) => setLinks((old) => old.map((l,n) => n===i ? {...l,type:e.target.value}:l))}>{PROJECT_LINK_TYPES.map((v) => <option key={v}>{v}</option>)}</select></label><Field label="Label" required value={link.label} onChange={(v) => setLinks((old) => old.map((l,n) => n===i ? {...l,label:v}:l))}/><Field label="URL" required validationPath={`links.${i}.url`} value={link.url} onChange={(v) => setLinks((old) => old.map((l,n) => n===i ? {...l,url:v}:l))}/><button className={styles.actionButton} type="button" onClick={() => setLinks((old) => old.filter((_,n) => n!==i))}>Remove link</button></div>)}<button className={styles.actionButton} type="button" onClick={() => setLinks((old) => [...old,{type:"live",label:"",url:"",position:old.length}])}>Add project link</button></div>
  </section>;
}
function Field({label,value,onChange,validationPath,required=false}:{label:string;value:string;onChange:(value:string)=>void;validationPath?:string;required?:boolean}) { return <label className={styles.field}><span>{label}</span><input data-validation-path={validationPath} required={required} type={label === "URL" ? "url" : "text"} value={value} onChange={(e)=>onChange(e.target.value)}/></label>; }
function ProjectFields({ block, media, path, update }: { block: Block; media: { id: string; filename: string }[]; path: string; update: (data: Record<string, unknown>) => void }) {
  const data = block.data; const set = (key:string,value:unknown) => update({...data,[key]:value}); const field = (key:string,label:string,area=false) => <label className={styles.field} key={key}><span>{label}</span>{area?<textarea data-validation-path={`${path}.data.${key}`} rows={3} value={String(data[key]??"")} onChange={(e)=>set(key,e.target.value)}/>:<input data-validation-path={`${path}.data.${key}`} value={String(data[key]??"")} onChange={(e)=>set(key,e.target.value)}/>}</label>;
  if (block.type === "rich_text") return field("content","Content",true);
  if (block.type === "quote") return <>{field("quote","Quote",true)}{field("author","Attribution")}</>;
  if (block.type === "image") return <label className={styles.field}><span>Image</span><select data-validation-path={`${path}.data.mediaId`} value={String(data.mediaId??"")} onChange={(e)=>set("mediaId",e.target.value)}><option value="">Select media</option>{media.map((m)=><option key={m.id} value={m.id}>{m.filename}</option>)}</select></label>;
  if (["problem_list","objective_list","technology_list"].includes(block.type)) { const items=Array.isArray(data.items)?data.items as string[]:[""]; return <>{items.map((v,i)=><label className={styles.field} key={i}><span>Item {i+1}</span><input data-validation-path={`${path}.data.items.${i}`} value={v} onChange={(e)=>set("items",items.map((x,n)=>n===i?e.target.value:x))}/></label>)}<button className={styles.actionButton} data-validation-path={`${path}.data.items`} type="button" onClick={()=>set("items",[...items,""])}>Add item</button></>; }
  if (block.type === "gallery") { const ids=Array.isArray(data.mediaIds)?data.mediaIds as string[]:[]; return <>{ids.map((id,i)=><label className={styles.field} key={i}><span>Image {i+1}</span><select data-validation-path={`${path}.data.mediaIds.${i}`} value={id} onChange={(e)=>set("mediaIds",ids.map((v,n)=>n===i?e.target.value:v))}><option value="">Select media</option>{media.map((m)=><option key={m.id} value={m.id}>{m.filename}</option>)}</select></label>)}<button className={styles.actionButton} data-validation-path={`${path}.data.mediaIds`} type="button" onClick={()=>set("mediaIds",[...ids,""])}>Add image</button></>; }
  const collection = block.type === "process_steps" ? "steps" : block.type === "metrics" ? "metrics" : block.type === "roadmap" ? "items" : "";
  if (collection) { const list=Array.isArray(data[collection])?data[collection] as Record<string,string>[]:[]; const keys=block.type==="process_steps"?["title","description"]:block.type==="metrics"?["value","label"]:["phase","title","description"]; return <>{list.map((row,i)=><div className={styles.canvasSubBlock} key={i}>{keys.map((key)=><label className={styles.field} key={key}><span>{key}</span><input data-validation-path={`${path}.data.${collection}.${i}.${key}`} value={row[key]??""} onChange={(e)=>set(collection,list.map((v,n)=>n===i?{...v,[key]:e.target.value}:v))}/></label>)}<button className={styles.actionButton} type="button" onClick={()=>set(collection,list.filter((_,n)=>n!==i))}>Remove item</button></div>)}<button className={styles.actionButton} data-validation-path={`${path}.data.${collection}`} type="button" onClick={()=>set(collection,[...list,Object.fromEntries(keys.map(k=>[k,""]))])}>Add item</button></>; }
  return <>{field("title","Title")}{field("content","Content",true)}</>;
}
